##### GET DISTRIBUTION INFO TO CHECK AUTOMATICALLY #####
- name: Set distribution info to map
  set_fact:
    my_map: "{{ my_map | combine({'distribution': ansible_distribution, 'distribution_version': ansible_distribution_version, 'distribution_major_version': ansible_distribution_major_version}) }}"
