---
- name: Check if VEP is installed properly
  include_role:
    name: if_vep_folder_exist
##### GET VEP VERSION INFO TO CHECK AUTOMATICALLY #####
- name: Call ./vep
  command: chdir=ensembl-vep ./vep
  register: VEP_info
- name: Read file .version/ensembl
  slurp:
    src: ensembl-vep/.version/ensembl
  register: ensembl_version_file_content
- name: Set VEP version info to map
  set_fact:
    my_map: "{{ my_map | combine({'ensembl_vep_version': VEP_info.stdout.split('\n')[9].split()[-1], 'major_vep_version': (ensembl_version_file_content['content'] | b64decode).split('\n')[0].split()[-1]}) }}"
